// Source-observed regressions: independent props, asymmetric firing, dive and transition keys.
import fs from 'node:fs/promises';import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{sourcePhase}from'./catalog.mjs';
globalThis.ProgressEvent??=class{};
const bytes=await fs.readFile(process.env.TANYA_MOTION_GLB||new URL('../../assets/hd/models/tanya/tanya-actions.glb',import.meta.url)),n=bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,20+n));g.images=[];g.textures=[];g.materials=[];for(const mesh of g.meshes)for(const p of mesh.primitives)delete p.material;g.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+n).toString('base64');
async function fixture(){const m=await new GLTFLoader().parseAsync(JSON.stringify(g),''),mix=new T.AnimationMixer(m.scene);return{m,point:name=>m.scene.getObjectByName(name).getWorldPosition(new T.Vector3()),at(name,p=0){mix.stopAllAction();const clip=m.animations.find(c=>c.name===name),a=mix.clipAction(clip);a.reset().setLoop(T.LoopOnce,1).play();a.clampWhenFinished=true;mix.setTime(Math.min(p,.999999)*clip.duration);m.scene.updateMatrixWorld(true);return Object.fromEntries(['Left','Right'].map(side=>[side,m.scene.getObjectByName('Tanya'+side+'Pistol')]));}};}
test('water movement is unarmed, water/prone shooting uses one pistol, standing restores both',async()=>{const{at}=await fixture();for(const name of ['swim','tread','wetidle1','wetidle2','wetdie1','wetdie2','paradrop','crawl'])for(const gun of Object.values(at(name)))assert.equal(gun.scale.x,0,name);for(const name of ['wetattack','fireprone']){const p=at(name);assert.equal(p.Left.scale.x,0);assert.equal(p.Right.scale.x,1);}for(const gun of Object.values(at('fireup')))assert.equal(gun.scale.x,1);});
test('one hand supports prone/water firing while the other aims',async()=>{const{at,point}=await fixture();at('fireprone');assert.ok(point('LeftHand').y<.16);assert.ok(point('RightHand').y>.26);at('wetattack');assert.ok(point('RightHand').y-point('LeftHand').y>.15);const a=point('LeftHand');at('wetattack',.4);assert.ok(a.distanceTo(point('LeftHand'))>.06,'free hand must scull');});
test('running holds the right gun up and passes the feet on source keys 2 and 5',async()=>{const{at,point}=await fixture();for(const i of [2,5]){at('walk',i/6);assert.ok(Math.abs(point('LeftFoot').z-point('RightFoot').z)<.26);assert.ok(point('RightHand').y-point('LeftHand').y>.25);}at('walk',1/6);assert.ok(Math.abs(point('LeftFoot').z-point('RightFoot').z)>.6);});
test('idle toss visibly leaves the hand and returns; drops settle after death',async()=>{const{at,point}=await fixture();function centre(mesh){const p=mesh.geometry.attributes.position,ids=mesh.geometry.index.array,v=new T.Vector3();for(const i of ids)v.add(new T.Vector3().fromBufferAttribute(p,i));return v.divideScalar(ids.length).applyMatrix4(mesh.matrixWorld);}let guns=at('idle2',7/15);assert.ok(centre(guns.Right).distanceTo(point('RightHand'))>.4,'pistol stuck to hand during toss');guns=at('idle2',12/15);assert.ok(centre(guns.Right).distanceTo(point('RightHand'))<.24,'catch must restore attachment');const a=centre(at('die1',.75).Right),b=centre(at('die1',.99).Right);assert.ok(a.distanceTo(b)<.001,'dropped gun follows dying hand');});
test('two source crouch keys and smooth transition endpoints are all reachable',async()=>{const{at,point}=await fixture();at('down',sourcePhase('down',0));const high=point('Hips').y;at('down',sourcePhase('down',1));const low=point('Hips').y;assert.ok(high>low+.15&&low>.30);at('up',sourcePhase('up',0));assert.ok(Math.abs(point('Hips').y-low)<.01);at('up',sourcePhase('up',1));assert.ok(Math.abs(point('Hips').y-high)<.01);at('down',1);const prone=point('Hips');at('prone');assert.ok(prone.distanceTo(point('Hips'))<.002);at('up',1);assert.ok(point('Hips').y>.90);});
test('water idles dive and recover, deaths end submerged, and variants differ',async()=>{const{at,point}=await fixture();for(const name of ['wetidle1','wetidle2']){at(name,0);const start=point('Head');at(name,.5);assert.ok(point('Head').y<start.y-.3);at(name,.999999);assert.ok(point('Head').distanceTo(start)<.005);}for(const name of ['wetdie1','wetdie2']){at(name,1);assert.ok(point('Head').y<-.9);}at('die1',.3);const a=point('Head');at('die2',.3);assert.ok(a.distanceTo(point('Head'))>.5);});
