// User found symmetric crawling legs, permanently held pistols and absent vest remap.
// Check source-key asymmetry, independently animated props and skin-attached cloth metadata.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import * as T from 'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';
globalThis.ProgressEvent??=class{};
const b=await fs.readFile(process.env.TANYA_MOTION_GLB||new URL('../../assets/hd/models/tanya/tanya-actions.glb',import.meta.url)),n=b.readUInt32LE(12),g=JSON.parse(b.subarray(20,20+n));
async function fixture(){const j=structuredClone(g);j.images=[];j.textures=[];j.materials=[];for(const m of j.meshes)for(const p of m.primitives)delete p.material;j.buffers[0].uri='data:application/octet-stream;base64,'+b.subarray(28+n).toString('base64');const m=await new GLTFLoader().parseAsync(JSON.stringify(j),''),mix=new T.AnimationMixer(m.scene);return {m,at(name,phase){mix.stopAllAction();const clip=m.animations.find(c=>c.name===name);mix.clipAction(clip).reset().play();mix.setTime(phase*clip.duration);m.scene.updateMatrixWorld(true);const out={};m.scene.traverse(o=>{if(o.isBone)out[o.name]=o.getWorldPosition(new T.Vector3());});return out;}};}
test('each of the six crawl keys keeps legs staggered and reverses the supporting side',async()=>{const {at}=await fixture(),keys=Array.from({length:6},(_,i)=>at('crawl',i/6));for(let i=0;i<6;i++){const p=keys[i];assert.ok(Math.abs(p.LeftFoot.z-p.RightFoot.z)>.07,`source key ${i} has averaged legs`);assert.ok(p.LeftFoot.y<.14&&p.RightFoot.y<.14,'feet leave ground');}assert.ok(keys[0].LeftFoot.z<keys[0].RightFoot.z-.25);assert.ok(keys[3].RightFoot.z<keys[3].LeftFoot.z-.25);assert.ok(keys[0].LeftHand.z>keys[0].RightHand.z+.15);assert.ok(keys[3].RightHand.z>keys[3].LeftHand.z+.15);});
test('crawl and its prone alias suppress separate pistols; firing restores them',async()=>{const {m,at}=await fixture(),gun=m.scene.getObjectByName('TanyaRightPistol');assert.ok(gun,'weapons must be independently controlled');for(const name of ['crawl','prone']){at(name,0);assert.equal(gun.scale.x,0);}at('fireprone',0);assert.equal(gun.scale.x,1);const body=g.meshes[0].primitives[0],pistol=g.meshes[1].primitives[0];assert.equal(body.attributes.POSITION,pistol.attributes.POSITION,'parts share position buffer');assert.equal(g.meshes.reduce((sum,m)=>sum+g.accessors[m.primitives[0].indices].count/3,0),29827);});
test('vest region exists in the delivered skin instead of an incorrectly scaled runtime height',async()=>{const {m}=await fixture();let body;m.scene.traverse(o=>{if(o.isSkinnedMesh&&o.geometry.attributes._team_mask)body=o;});assert.ok(body);const mask=body.geometry.attributes._team_mask;let selected=0;for(let i=0;i<mask.count;i++)selected+=mask.getX(i);assert.ok(selected>500&&selected<mask.count*.35,'cloth eligibility empty or covers most of the body');});
