// Regression: HD Tanya previously had no real animated left foot or complete SHP mapping.
// Validate delivered skin motion and water/prone clips, not merely menu labels.
import{pathToFileURL}from'node:url';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import * as T from 'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{sequences,sourceFrame}from'./catalog.mjs';
globalThis.ProgressEvent??=class{};
const file=process.env.TANYA_MOTION_GLB?pathToFileURL(process.env.TANYA_MOTION_GLB):new URL('../../assets/hd/models/tanya/tanya-actions.glb',import.meta.url),bytes=await fs.readFile(file),n=bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,20+n));
async function model(){const j=structuredClone(g);j.images=[];j.textures=[];j.materials=[];for(const m of j.meshes)for(const p of m.primitives)delete p.material;j.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+n).toString('base64');return new GLTFLoader().parseAsync(JSON.stringify(j),'');}
test('all source actions have shared-geometry skeletal clips and valid durations',()=>{assert.equal(bytes.readUInt32LE(8),bytes.length);assert.equal(g.skins.length,1);assert.equal(g.skins[0].joints.length,24);assert.equal(g.meshes.length,1);for(const[name,[,count]]of Object.entries(sequences)){const clip=g.animations.find(c=>c.name===name);assert.ok(clip,name);assert.equal(clip.extras.sourceSequence[1],count);assert.ok(clip.channels.length>=24);assert.ok(Math.abs(g.accessors[clip.samplers[0].input].max[0]-count/12)<1e-6);}});
test('both feet move and exchange the lead during a running cycle',async()=>{const p=await model(),m=new T.AnimationMixer(p.scene),c=p.animations.find(c=>c.name==='walk');m.clipAction(c).play();const samples=[];for(const phase of [0,.25,.5,.75]){m.setTime(c.duration*phase);p.scene.updateMatrixWorld(true);samples.push(['LeftFoot','RightFoot'].map(n=>p.scene.getObjectByName(n).getWorldPosition(new T.Vector3())));}for(let foot=0;foot<2;foot++)assert.ok(samples[0][foot].distanceTo(samples[2][foot])>.25);assert.ok((samples[1][0].z-samples[1][1].z)*(samples[3][0].z-samples[3][1].z)<0);});
test('swim arms change; prone and standing shots have distinct body heights',async()=>{const p=await model(),m=new T.AnimationMixer(p.scene);function at(name,t=0){m.stopAllAction();m.clipAction(p.animations.find(c=>c.name===name)).reset().play();m.setTime(t);p.scene.updateMatrixWorld(true);return Object.fromEntries(['Hips','Head','LeftHand','RightHand'].map(n=>[n,p.scene.getObjectByName(n).getWorldPosition(new T.Vector3())]));}const standing=at('fireup'),prone=at('fireprone');assert.ok(standing.Hips.y>.8);assert.ok(prone.Hips.y<.3);assert.ok(prone.Head.y<standing.Head.y-.5);assert.ok(standing.LeftHand.z>.30&&standing.RightHand.z>.30);const a=at('swim'),b=at('swim',2/12);assert.ok(a.LeftHand.distanceTo(b.LeftHand)>.15);assert.ok(a.RightHand.distanceTo(b.RightHand)>.15);});
test('named frame slots and water facings extend beyond the old 512-frame limit',async()=>{const m=JSON.parse(await fs.readFile(new URL('../../assets/hd/sprites/manifest.json',import.meta.url))),s=m.sprites.tany;assert.equal(s.animationClock,'source');assert.equal(s.frames,619);assert.equal(s.frameRects.length,619);assert.equal(s.unmappedFrames.length,104);assert.equal(sourceFrame('wetattack',7,5),601);for(const[name,[,count,stride]]of Object.entries(sequences))for(let d=0;d<(stride?8:1);d++)for(let f=0;f<count;f++){const i=sourceFrame(name,d,f),[x,y,w,h]=s.frameRects[i];if(name.startsWith('wetdie')&&f>=16)continue;assert.ok(w>1&&h>1,`${name} ${d} ${f}`);assert.ok(x>=0&&y>=0&&x+w<=s.width&&y+h<=s.height);}assert.deepEqual(s.sequences,sequences);});
test('skin weights remain normalized and animation samples finite',async()=>{const p=await model();let mesh;p.scene.traverse(o=>{if(o.isSkinnedMesh)mesh=o;});const w=mesh.geometry.attributes.skinWeight;for(let i=0;i<w.count;i++)assert.ok(Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)<.001);for(const c of p.animations)for(const t of c.tracks)assert.ok(t.values.every(Number.isFinite),t.name);});
