// User reported sliding running feet and an incoherent swimming kick.
// Verify delivered bone contacts and source-referenced swim keys, not interpolation settings.
import fs from 'node:fs/promises';import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';
globalThis.ProgressEvent??=class{};
const bytes=await fs.readFile(process.env.TANYA_MOTION_GLB||new URL('../../assets/hd/models/tanya/tanya-actions.glb',import.meta.url)),n=bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,20+n));g.images=[];g.textures=[];g.materials=[];for(const mesh of g.meshes)for(const p of mesh.primitives)delete p.material;g.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(28+n).toString('base64');
async function fixture(){const m=await new GLTFLoader().parseAsync(JSON.stringify(g),''),mixer=new T.AnimationMixer(m.scene);return {m,at(name,phase){mixer.stopAllAction();const clip=m.animations.find(c=>c.name===name);assert.ok(clip,name);mixer.clipAction(clip).reset().play();mixer.setTime(Math.min(.999999,phase)*clip.duration);m.scene.updateMatrixWorld(true);const p={};m.scene.traverse(b=>{if(b.isBone)p[b.name]=b.getWorldPosition(new T.Vector3());});return p;}};}
test('support foot holds the ground while the body advances; swing foot clears it',async()=>{const {at}=await fixture();for(const [side,offset]of [['Left',.77],['Right',.27]]){const a=at('walk',offset+.04),b=at('walk',offset+.17);assert.ok(Math.abs(a[side+'Foot'].y-b[side+'Foot'].y)<.012,'planted ankle changes height');assert.ok(Math.abs(b[side+'Foot'].z-a[side+'Foot'].z+2.4*.13)<.015,'support foot slides after root travel is added');const swing=at('walk',(offset+.62)%1);assert.ok(swing[side+'Foot'].y>a[side+'Foot'].y+.16,'swing must clear the ground');}});
test('swim keys extend and sweep both arms while narrow feet kick alternately',async()=>{const {at}=await fixture(),keys=Array.from({length:6},(_,i)=>at('swim',i/6));for(const p of keys)assert.ok(Math.abs(p.LeftFoot.x-p.RightFoot.x)<.35,'frog kick is not supported by the source');assert.ok((keys[0].LeftFoot.y-keys[0].RightFoot.y)*(keys[3].LeftFoot.y-keys[3].RightFoot.y)<0,'kick must reverse');assert.ok(keys[3].LeftHand.z>keys[1].LeftHand.z+.25,'recover then extend');assert.ok(Math.abs(keys[0].LeftHand.x-keys[0].RightHand.x)>Math.abs(keys[3].LeftHand.x-keys[3].RightHand.x)+.30,'wide pull and narrow reach must differ');});
test('swim cadence allows a full stroke and loop seam is continuous',async()=>{const {m,at}=await fixture();assert.ok(m.animations.find(c=>c.name==='swim').duration>=1.2,'six source slots must not force a half-second stroke');for(const name of ['walk','swim','tread']){const a=at(name,0),b=at(name,.999);for(const bone of ['LeftFoot','RightFoot','LeftHand','RightHand'])assert.ok(a[bone].distanceTo(b[bone])<.025,`${name} ${bone} seam`);}});
test('swim to tread transition preserves waterline and endpoint pose',async()=>{const {at}=await fixture(),a=at('swim',0),b=at('swimstop',0),c=at('swimstop',.999999),d=at('tread',0),e=at('swimstart',.999999);for(const bone of ['Hips','LeftHand','RightFoot']){assert.ok(a[bone].distanceTo(b[bone])<.005);d[bone].y-=.90;assert.ok(c[bone].distanceTo(d[bone])<.005,`${bone} waterline`);assert.ok(a[bone].distanceTo(e[bone])<.005);}});
