// Browser regression for source-key crawl inspection, prop switching and actual Canvas remap.
// Captures local-only reference screenshots; never publishes original artwork.
import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs/promises';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:4180',out='.cache/crawl-inspection';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/');await page.waitForFunction(()=>window.__motion);await page.selectOption('#action','crawl');await page.selectOption('#facing','0');await page.click('#play');
 for(let i=0;i<6;i++){await page.locator('#seek').fill(String(i));await page.locator('#seek').dispatchEvent('input');assert.match(await page.locator('#readout').innerText(),new RegExp(`SHP ${86+i}`));assert.equal(await page.evaluate(()=>__motion.gltf.scene.getObjectByName('TanyaRightPistol').scale.x),0);await page.screenshot({path:`${out}/crawl-n-${i}.png`});}
 await page.selectOption('#facing','2');await page.locator('#seek').fill('0');await page.locator('#seek').dispatchEvent('input');await page.screenshot({path:out+'/crawl-side-red.png'});
 await page.locator('#team-color').fill('#286ce5');await page.locator('#team-color').dispatchEvent('input');await page.screenshot({path:out+'/crawl-side-blue.png'});
 await page.selectOption('#action','fireprone');assert.equal(await page.evaluate(()=>__motion.gltf.scene.getObjectByName('TanyaRightPistol').scale.x),1);
 await page.goto(origin+'/canvas/');await page.waitForFunction(()=>window.__hd?.ready);await page.selectOption('#frame-action','crawl');await page.selectOption('#frame-facing','0');
 for(let i=0;i<6;i++){await page.locator('#frame-step').fill(String(i));await page.locator('#frame-step').dispatchEvent('input');const p=await page.evaluate(()=>{const h=__hd,e=h.actors[7],copy=h.comparisons.find(p=>p.source.id===e.id).copy,a=h.renderer.entityPresentation(e),b=h.renderer.entityPresentation(copy);return {frame:a.frame,old:b.frame,different:a.sprite.src!==b.sprite.src};});assert.deepEqual(p,{frame:86+i,old:86+i,different:true});}
 const remap=await page.evaluate(()=>{const h=__hd,s=h.hd.sprites.tany,r=h.renderer;const pixels=color=>{const im=r.coloredSprite(s,color),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);return ctx.getImageData(0,0,c.width,c.height).data;};const a=pixels('#e52d36'),b=pixels('#286ce5'),im=h.assets.images.get(s.remapMaskSrc),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const mask=ctx.getImageData(0,0,c.width,c.height).data;let outside=0,changed=0;const frames=[];for(let f=86;f<134;f++){const[x,y,w,hh]=s.frameRects[f];let count=0;for(let yy=y;yy<y+hh;yy++)for(let xx=x;xx<x+w;xx++){const i=(yy*c.width+xx)*4;if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2]){count++;changed++;if(!mask[i+3])outside++;}}frames.push(count);}return {outside,changed,frames};});assert.equal(remap.outside,0);assert.ok(remap.frames.every(n=>n>30),'every crawl frame/facing needs visible cloth remap');
 await page.locator('#own-color').fill('#e52d36');await page.locator('#own-color').dispatchEvent('input');await page.screenshot({path:out+'/canvas-crawl-red.png'});await page.locator('#own-color').fill('#286ce5');await page.locator('#own-color').dispatchEvent('input');await page.screenshot({path:out+'/canvas-crawl-blue.png'});
 assert.deepEqual(errors,[]);console.log('Crawl browser passed: six keys, independent pistols, same-map source alignment, nonempty remap in 48 views; no changed pixels outside mask.',remap.changed);
}finally{await browser.close();}
