// Synchronized SHP frame / real skinned GLB inspection. No game simulation here.
import * as T from 'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
import{sequences,labels,fps,isOnce,sourceFrame,sourceFacing}from'./catalog.mjs';import{bakeAtlas}from'./bake-atlas.mjs';
const $=id=>document.getElementById(id),stage=$('stage'),renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#20262c');scene.add(new T.HemisphereLight(0xe8efff,0x4d5560,2));const sun=new T.DirectionalLight(0xfff5e8,2.4);sun.position.set(3,5,4);scene.add(sun);const camera=new T.OrthographicCamera(-1,1,1,-1,.01,100),controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.8,0);const group=new T.Group();scene.add(group);
const source=new Image();source.src='/original-tanya.png';await source.decode();
const gltf=await new GLTFLoader().loadAsync('/tanya-actions.glb');group.add(gltf.scene);const mixer=new T.AnimationMixer(gltf.scene),clips=Object.fromEntries(gltf.animations.map(c=>[c.name,c]));let action,phase=0,age=0,playing=true,smooth=true;
const helper=new T.SkeletonHelper(gltf.scene);helper.visible=false;group.add(helper);
const shown=Object.keys(labels).filter(n=>!['guard','panic','die3','die4','die5'].includes(n));$('action').replaceChildren(...shown.map(n=>new Option(labels[n],n)));$('action').value='walk';$('facing').replaceChildren(...['北','西北','西','西南','南','东南','东','东北'].map((n,i)=>new Option(n,String(i))));$('facing').value='4';
function view(){camera.position.set(3,3*Math.sqrt(2/3)+.8,3);controls.target.set(0,.8,0);controls.update();}
function select(){phase=0;age=0;if(action)action.stop();action=mixer.clipAction(clips[$('action').value]);action.reset().play();$('seek').max=sequences[$('action').value][1]-1;sample();}
function sample(){const name=$('action').value,count=sequences[name][1],step=Math.min(count-1,Math.floor(phase*count)),dir=Number($('facing').value);mixer.setTime(playing&&smooth?phase*count/fps:step/fps);gltf.scene.updateMatrixWorld(true);group.rotation.y=-3*Math.PI/4+dir*Math.PI/4;
 const index=sourceFrame(name,dir,step),ctx=$('reference').getContext('2d');ctx.clearRect(0,0,390,330);ctx.imageSmoothingEnabled=false;ctx.drawImage(source,index%16*130,Math.floor(index/16)*110,130,110,0,0,390,330);$('seek').value=step;$('readout').textContent=`24 骨骼 · ${labels[name]} · ${step+1}/${count} · ${(count/fps).toFixed(2)} 秒 · SHP ${index}`;$('source').textContent=`原版帧 ${index}，${sequences[name][2]?'8 朝向':'单朝向参考'}；12 fps 预览时钟。`;}
$('action').onchange=()=>{const n=$('action').value;if(!sequences[n][2])$('facing').value=sourceFacing(n);select();};$('facing').onchange=sample;$('play').onclick=()=>{playing=!playing;age=phase*sequences[$('action').value][1]/fps;$('play').textContent=playing?'暂停':'播放';};$('seek').oninput=()=>{playing=false;$('play').textContent='播放';phase=Number($('seek').value)/sequences[$('action').value][1];sample();};$('interpolation').onclick=()=>{smooth=!smooth;$('interpolation').textContent=smooth?'平滑播放':'原帧步进';sample();};$('bones').onclick=()=>helper.visible=!helper.visible;$('view').onclick=view;
if(!['127.0.0.1','localhost'].includes(location.hostname))$('bake').hidden=true;
$('bake').onclick=async()=>{playing=false;$('play').textContent='播放';$('bake').disabled=true;try{const result=await bakeAtlas(gltf,t=>$('bake-status').textContent=t);$('bake-status').textContent=result;}catch(e){$('bake-status').textContent=String(e);}finally{$('bake').disabled=false;select();}};
view();select();let last=performance.now();function draw(now){requestAnimationFrame(draw);const dt=Math.min((now-last)/1000,.05)*Number($('speed').value);last=now;if(playing){const name=$('action').value,duration=sequences[name][1]/fps;age+=dt;phase=Math.min((age%(duration+(isOnce(name)?.75:0)))/duration,.999999);sample();}const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);const half=Math.max(1.13,1.35*h/w);camera.left=-half*w/h;camera.right=half*w/h;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();renderer.render(scene,camera);}requestAnimationFrame(draw);
